### ISSUE TITLE
Add a selector for controlling no. of resource display box

### ISSUE THREAD

**Issue by BossaGroove** [BossaGroove/KanColleViewer#1]

**Comment by gakada** [comment]
In https://github.com/gakada/KanColleViewer/commit/c6138045c9948f54189821bce5e66276dbb69dff I added 7th "blank" selector, so it's possible to hide materials like this (may also change `Generic.MetroComboBox.xaml` to only show arrows on mouseover):

![2016-01-17_08-12-02](https://cloud.githubusercontent.com/assets/13043588/12375079/6c7fe9e0-bcf5-11e5-948f-0dd5afe83040.png)

Thought you may also consider it.

**Comment by BossaGroove** [comment]
Ah it's a cool alternate way to do so,
coz actually i'm not a c# guy and not sure how to hide the element completely,
this issue has been left untouched for quite a while

thanks for the hint 👍

**Comment by BossaGroove** [comment]
https://github.com/BossaGroove/KanColleViewer/commit/be8aa2f22577c324c2eb52a835a79b18cc590c1f
